<a href="https://colab.research.google.com/github/gvc0461082002/30-seconds-of-code/blob/master/pytorch_artificial_intelligence_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
! nvidia-smi


Sat Oct 24 19:32:13 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.23.05    Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   44C    P8     9W /  70W |      0MiB / 15079MiB |      0%      Default |
|                               |                      |                 ERR! |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [4]:
!pip --version

pip 19.3.1 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)


In [5]:
pip install torch==1.6.0+cu101 torchvision==0.7.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html

Looking in links: https://download.pytorch.org/whl/torch_stable.html


In [ ]:
import torch
import numpy as np


In [7]:
torch.ones((2,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
torch.ones((2,3),dtype=torch.int8)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int8)

In [10]:
torch.zeros((2,3),dtype=torch.int8)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int8)

In [11]:
torch.full((2,3),3.14159265)

tensor([[3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416]])

In [12]:
torch.empty((2,3))

tensor([[1.8505e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 6.4460e-44]])

In [13]:
torch.rand((2,3))

tensor([[0.7882, 0.4338, 0.4745],
        [0.3016, 0.0308, 0.9354]])

In [14]:
torch.randn((2,3))

tensor([[-0.7105,  1.0881, -0.4271],
        [ 1.1911, -2.0256, -0.3061]])

In [16]:
torch.randint(10,100,(2,3))

tensor([[42, 53, 52],
        [44, 76, 81]])

In [17]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [18]:
torch.as_tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [20]:
a=torch.tensor([[1,2,3],[4,5,6]])

In [22]:
a.dtype

torch.int64

In [23]:
a.shape

torch.Size([2, 3])

In [26]:
b=torch.ones_like(a)

In [27]:
b.dtype

torch.int64

In [28]:
b.shape

torch.Size([2, 3])

In [29]:
b

tensor([[1, 1, 1],
        [1, 1, 1]])

In [30]:
a.new_full((2,2),3.)

tensor([[3, 3],
        [3, 3]])